module.exports = {
    'App.js': require('./App.js'),
    'index.js': require('./index.js'),
    'store.js': require('./store/index.js'),
    'index.scss': require('./sass/index.js'),
    '_base.scss': require('./sass/components/_base.js'),
    '_header.scss': require('./sass/components/_header.js'),
    'index.js': require('./reducers/index.js'),
    'Base.js': require('./models/Base.js'),
    'baseContainer.js': require('./containers/baseContainer.js'),
    'action-types.js': require('./constants/action-types.js'),
    'routes.js': require('./config/routes.js'),
    'Header.js': require('./components/Header.js'),
    'Home.js': require('./components/Home.js'),
    'List.js': require('./components/List.js'),
    'index.js': require('./actions/index.js'),
  }